/*
 * File: app/view/ui/BtnImprimir.js
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('usoslectura.view.ui.BtnImprimir', {
	extend: 'Ext.button.Button',

	id: 'btnImprimir',
	iconCls: 'print-icon',
	text: 'Imprimir',

	initComponent: function() {
		var me = this;

		me.callParent(arguments);
	}
});