/*
 * File: designer.js
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
	enabled: true
});

Ext.application({
	name: 'fichalectura',

	launch: function() {
		Ext.QuickTips.init();

		var cmp1 = Ext.create('fichalectura.view.FichaSenagua', {
			renderTo: Ext.getBody()
		});
		cmp1.show();
	}
});
