/*
 * File: app/view/ui/BtnGuardar.js
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sisconse.view.ui.BtnGuardar', {
	extend: 'Ext.button.Button',

	id: 'btnGuardar',
	iconCls: 'save-icon',
	text: 'Guardar',

	initComponent: function() {
		var me = this;

		me.callParent(arguments);
	}
});