/*
 * File: app/store/Cuencas.js
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sisconse.store.Cuencas', {
	extend: 'Ext.data.Store',

	constructor: function(cfg) {
		var me = this;
		cfg = cfg || {};
		me.callParent([Ext.apply({
			storeId: 'Cuencas',
			pageSize: 12,
			proxy: {
				type: 'ajax',
				url: 'app/data/cuencas.php',
				reader: {
					type: 'json',
					root: 'data'
				}
			},
			fields: [
				{
					name: 'hid_codigo'
				},
				{
					name: 'hid_nombre'
				}
			]
		}, cfg)]);

		this.load();
	}
});