/*
 * File: app/store/SiNo.js
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sisconse.store.SiNo', {
	extend: 'Ext.data.Store',

	constructor: function(cfg) {
		var me = this;
		cfg = cfg || {};
		me.callParent([Ext.apply({
			storeId: 'SiNo',
			data: [
				{
					sino_value: '0',
					'sino_display': 'No'
				},
				{
					'sino_value': '1',
					'sino_display': 'Si'
				}
			],
			proxy: {
				type: 'ajax',
				reader: {
					type: 'array'
				}
			},
			fields: [
				{
					name: 'sino_value'
				},
				{
					name: 'sino_display'
				}
			]
		}, cfg)]);
	}
});