/*
 * File: app/view/ui/FichaSenagua.js
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('usos.view.ui.FichaSenagua', {
	extend: 'Ext.form.Panel',
	requires: [
		'usos.view.BtnGuardar'
	],

	border: 0,
	height: Ext.Element.getDocumentHeight(),
	id: 'FichaSenagua',
	itemId: 'FichaSenagua',
	width: 1265,
	autoScroll: true,
	layout: {
		type: 'absolute'
	},
	frameHeader: false,
	title: '',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			dockedItems: [
				{
					xtype: 'toolbar',
					id: 'toolbar',
					autoScroll: true,
					enableOverflow: true,
					dock: 'top',
					items: [
						{
							xtype: 'btnguardar'
						},
						{
							xtype: 'tbseparator',
							id: 'separador'
						}
					]
				}
			],
			items: [
				{
					xtype: 'fieldcontainer',
					height: 194,
					width: 1244,
					layout: {
						type: 'absolute'
					},
					fieldLabel: '',
					x: 0,
					y: 0,
					items: [
						{
							xtype: 'image',
							height: 80,
							itemId: 'CbLogo',
							width: 770,
							src: '../ficha/legal/assets/images/senagua.png',
							x: 10,
							y: 10
						},
						{
							xtype: 'textfield',
							width: 200,
							inputId: 'CbFormularioNo',
							name: 'con_formulario',
							fieldLabel: 'FORMULARIO No',
							labelAlign: 'right',
							allowBlank: false,
							x: 790,
							y: 10
						},
						{
							xtype: 'textfield',
							width: 450,
							inputId: 'CbResponsable',
							name: 'con_responsable_datos',
							fieldLabel: 'RESPONSABLE',
							labelAlign: 'right',
							emptyText: '',
							x: 790,
							y: 40
						},
						{
							xtype: 'datefield',
							inputId: 'CbFecha',
							name: 'con_fecha_toma_datos',
							fieldLabel: 'FECHA',
							labelAlign: 'right',
							emptyText: '',
							format: 'Y-m-d',
							x: 790,
							y: 70
						},
						{
							xtype: 'combobox',
							width: 320,
							inputId: 'CbProvincia',
							name: 'dpa_provincia',
							fieldLabel: 'PROVINCIA',
							labelAlign: 'right',
							labelWidth: 70,
							displayField: 'dpa_descripcion',
							forceSelection: true,
							queryMode: 'local',
							store: 'Provincias',
							valueField: 'dpa_codigo',
							x: 90,
							y: 100
						},
						{
							xtype: 'combobox',
							width: 360,
							inputId: 'CbCanton',
							name: 'dpa_canton',
							fieldLabel: 'CANTON',
							labelAlign: 'right',
							labelWidth: 80,
							displayField: 'dpa_descripcion',
							forceSelection: true,
							queryMode: 'local',
							store: 'Cantones',
							valueField: 'dpa_codigo',
							x: 420,
							y: 100
						},
						{
							xtype: 'combobox',
							width: 450,
							inputId: 'CbParroquia',
							name: 'dpa_parroquia',
							fieldLabel: 'PARROQUIA',
							labelAlign: 'right',
							allowBlank: false,
							displayField: 'dpa_descripcion',
							forceSelection: true,
							queryMode: 'local',
							store: 'Parroquias',
							valueField: 'dpa_codigo',
							x: 790,
							y: 100
						},
						{
							xtype: 'combobox',
							width: 400,
							inputId: 'CbSistemaHidrografico',
							name: 'hid_id',
							fieldLabel: 'SISTEMA HIDROGRAFICO',
							labelAlign: 'right',
							labelWidth: 150,
							displayField: 'hid_nombre',
							forceSelection: true,
							queryMode: 'local',
							store: 'Sistemas',
							valueField: 'hid_codigo',
							x: 10,
							y: 130
						},
						{
							xtype: 'combobox',
							width: 350,
							inputId: 'CbCuenca',
							name: 'cue_id',
							fieldLabel: 'CUENCA',
							labelAlign: 'right',
							labelWidth: 70,
							displayField: 'hid_nombre',
							forceSelection: true,
							queryMode: 'local',
							store: 'Cuencas',
							valueField: 'hid_codigo',
							x: 430,
							y: 130
						},
						{
							xtype: 'combobox',
							width: 450,
							inputId: 'CbSubcuenca',
							name: 'sub_id',
							fieldLabel: 'SUBCUENCA',
							labelAlign: 'right',
							displayField: 'hid_nombre',
							forceSelection: true,
							queryMode: 'local',
							store: 'Subcuencas',
							valueField: 'hid_codigo',
							x: 790,
							y: 130
						},
						{
							xtype: 'combobox',
							width: 410,
							inputId: 'CbMicrocuenca',
							name: 'mic_id',
							fieldLabel: 'MICROCUENCA',
							labelAlign: 'right',
							labelWidth: 160,
							displayField: 'hid_nombre',
							forceSelection: true,
							queryMode: 'local',
							store: 'Microcuencas',
							valueField: 'hid_codigo',
							x: 0,
							y: 160
						},
						{
							xtype: 'numberfield',
							width: 290,
							inputId: 'CbPfastetter',
							name: 'pfastetter',
							fieldLabel: 'CODIGO PFASTETTER',
							labelAlign: 'right',
							labelWidth: 140,
							allowDecimals: false,
							minValue: 0,
							x: 490,
							y: 160
						}
					]
				},
				{
					xtype: 'fieldset',
					height: 110,
					id: 'Actualizaciones',
					width: 1230,
					layout: {
						type: 'absolute'
					},
					title: 'I USOS DE HECHO',
					x: 10,
					y: 200,
					items: [
						{
							xtype: 'textfield',
							width: 800,
							inputId: 'ActAutorizadoInicial',
							name: 'rio_autoriz_inicial_id',
							fieldLabel: 'NOMBRE DE USUARIO',
							labelAlign: 'right',
							labelWidth: 130,
							emptyText: '',
							x: 10,
							y: 10
						},
						{
							xtype: 'textfield',
							width: 290,
							inputId: 'ActTelefonoCasa',
							name: 'rio_telefono',
							fieldLabel: 'TELEFONO DE CASA',
							labelAlign: 'right',
							labelWidth: 120,
							x: 20,
							y: 40
						},
						{
							xtype: 'textfield',
							width: 180,
							inputId: 'ActCelular',
							name: 'rio_celular',
							fieldLabel: 'CELULAR',
							labelAlign: 'right',
							labelWidth: 60,
							vtype: 'alphanum',
							x: 330,
							y: 40
						},
						{
							xtype: 'textfield',
							width: 270,
							inputId: 'ActEmail',
							name: 'rio_email',
							fieldLabel: 'EMAIL',
							labelAlign: 'right',
							labelWidth: 40,
							vtype: 'email',
							x: 540,
							y: 40
						}
					]
				},
				{
					xtype: 'fieldset',
					height: 1160,
					id: 'Usos',
					width: 1230,
					layout: {
						type: 'absolute'
					},
					title: 'II USOS DEL AGUA',
					x: 10,
					y: 340,
					items: [
						{
							xtype: 'checkboxgroup',
							height: 55,
							id: 'UsUsosAgua',
							width: 1015,
							layout: {
								type: 'absolute'
							},
							fieldLabel: '',
							name: 'UsUsosAgua',
							x: 10,
							y: 5,
							items: [
								{
									xtype: 'checkboxfield',
									inputId: 'UsConsumoHumano',
									name: 'dom_consumo_humano_yn',
									boxLabel: 'Consumo humano',
									inputValue: 1,
									uncheckedValue: 0,
									x: 0,
									y: 0
								},
								{
									xtype: 'checkboxfield',
									inputId: 'UsPiscicola',
									name: 'pis_piscicola_yn',
									boxLabel: 'Piscícola',
									inputValue: 1,
									uncheckedValue: 0,
									x: 140,
									y: 0
								},
								{
									xtype: 'checkboxfield',
									inputId: 'UsAguaEnvasada',
									name: 'env_agua_envasada_yn',
									boxLabel: 'Agua envasada',
									inputValue: 1,
									uncheckedValue: 0,
									x: 250,
									y: 0
								},
								{
									xtype: 'checkboxfield',
									inputId: 'UsTermales',
									name: 'ter_termales_yn',
									boxLabel: 'Termales',
									inputValue: 1,
									uncheckedValue: 0,
									x: 380,
									y: 0
								},
								{
									xtype: 'checkboxfield',
									inputId: 'UsIndustria',
									name: 'ind_industria_yn',
									boxLabel: 'Industria',
									inputValue: 1,
									uncheckedValue: 0,
									x: 480,
									y: 0
								},
								{
									xtype: 'checkboxfield',
									inputId: 'UsRiego',
									name: 'rie_riego_yn',
									boxLabel: 'Riego',
									inputValue: 1,
									uncheckedValue: 0,
									x: 570,
									y: -1
								},
								{
									xtype: 'checkboxfield',
									inputId: 'UsFuerzaMecanica',
									name: 'mec_fuerza_mecanica_yn',
									boxLabel: 'Fuerza mecánica',
									inputValue: 1,
									uncheckedValue: 0,
									x: 0,
									y: 20
								},
								{
									xtype: 'checkboxfield',
									inputId: 'UsAbrevadero',
									name: 'abr_abrevadero_yn',
									boxLabel: 'Abrevadero',
									inputValue: 1,
									uncheckedValue: 0,
									x: 140,
									y: 20
								},
								{
									xtype: 'checkboxfield',
									inputId: 'UsHidroelectricas',
									name: 'hid_hidrolectricas_yn',
									boxLabel: 'Hidroeléctricas',
									inputValue: 1,
									uncheckedValue: 0,
									x: 250,
									y: 20
								},
								{
									xtype: 'checkboxfield',
									inputId: 'UsTuristico',
									name: 'tur_turistico_yn',
									boxLabel: 'Turístico',
									inputValue: 1,
									uncheckedValue: 0,
									x: 380,
									y: 20
								},
								{
									xtype: 'checkboxfield',
									inputId: 'UsOtros',
									name: 'otros_yn',
									boxLabel: 'Otros',
									inputValue: 1,
									uncheckedValue: 0,
									x: 480,
									y: 20
								}
							]
						},
						{
							xtype: 'fieldset',
							height: 70,
							id: 'a-consumo-humano',
							width: 1190,
							layout: {
								type: 'absolute'
							},
							title: 'A. CONSUMO HUMANO',
							x: 10,
							y: 60,
							items: [
								{
									xtype: 'numberfield',
									width: 230,
									inputId: 'UsACaudalMedido',
									name: 'dom_caudal_medido',
									fieldLabel: 'CAUDAL MEDIDO (l/s)',
									labelAlign: 'right',
									labelWidth: 140,
									minValue: 0,
									x: -8,
									y: 5
								},
								{
									xtype: 'numberfield',
									width: 220,
									inputId: 'UsAPoblacion',
									name: 'dom_poblacion',
									fieldLabel: 'POBLACION (Hab)',
									labelAlign: 'right',
									labelWidth: 110,
									allowDecimals: false,
									minValue: 0,
									x: 255,
									y: 5
								},
								{
									xtype: 'numberfield',
									width: 220,
									inputId: 'UsADotacion',
									name: 'dom_dotacion',
									fieldLabel: 'DOTACION (l/s/Ha)',
									labelAlign: 'right',
									labelWidth: 120,
									minValue: 0,
									x: 510,
									y: 5
								}
							]
						},
						{
							xtype: 'fieldset',
							height: 220,
							id: 'b-piscicolas',
							width: 1190,
							layout: {
								type: 'absolute'
							},
							title: 'B. PISCICOLAS',
							x: 10,
							y: 150,
							items: [
								{
									xtype: 'numberfield',
									width: 230,
									inputId: 'UsBCaudalMedido',
									name: 'pis_caudal_medido',
									fieldLabel: 'CAUDAL MEDIDO (l/s)',
									labelAlign: 'right',
									labelWidth: 140,
									minValue: 0,
									x: -7,
									y: 5
								},
								{
									xtype: 'fieldcontainer',
									height: 64,
									id: 'UsBAcuacultura',
									width: 749,
									layout: {
										type: 'absolute'
									},
									fieldLabel: 'ACUACULTURA (Producción anual)',
									labelWidth: 140,
									x: 275,
									y: 0,
									items: [
										{
											xtype: 'combobox',
											width: 130,
											name: 'pis_truchas_yn',
											fieldLabel: 'Truchas',
											labelAlign: 'right',
											labelWidth: 50,
											displayField: 'sino_display',
											queryMode: 'local',
											store: 'SiNo',
											valueField: 'sino_value',
											x: -36,
											y: 5
										},
										{
											xtype: 'numberfield',
											width: 75,
											inputId: 'UsBATruchas',
											name: 'pis_truchas_anual',
											fieldLabel: '',
											labelAlign: 'right',
											labelWidth: 50,
											allowDecimals: false,
											minValue: 0,
											x: 20,
											y: 35
										},
										{
											xtype: 'combobox',
											width: 130,
											name: 'pis_tilapias_yn',
											fieldLabel: 'Tilapias',
											labelAlign: 'right',
											labelWidth: 50,
											displayField: 'sino_display',
											queryMode: 'local',
											store: 'SiNo',
											valueField: 'sino_value',
											x: 105,
											y: 5
										},
										{
											xtype: 'numberfield',
											width: 75,
											inputId: 'UsBATilapias',
											name: 'pis_tilapias_anual',
											fieldLabel: '',
											labelAlign: 'right',
											labelWidth: 50,
											allowDecimals: false,
											minValue: 0,
											x: 160,
											y: 35
										},
										{
											xtype: 'combobox',
											width: 140,
											name: 'pis_camarones_yn',
											fieldLabel: 'Camarones',
											labelAlign: 'right',
											labelWidth: 60,
											displayField: 'sino_display',
											queryMode: 'local',
											store: 'SiNo',
											valueField: 'sino_value',
											x: 255,
											y: 5
										},
										{
											xtype: 'numberfield',
											width: 75,
											inputId: 'UsBACamarones',
											name: 'pis_camarones_anual',
											fieldLabel: '',
											labelAlign: 'right',
											labelWidth: 70,
											allowDecimals: false,
											minValue: 0,
											x: 320,
											y: 35
										},
										{
											xtype: 'combobox',
											width: 130,
											name: 'pis_otros_yn',
											fieldLabel: 'Otros',
											labelAlign: 'right',
											labelWidth: 50,
											displayField: 'sino_display',
											queryMode: 'local',
											store: 'SiNo',
											valueField: 'sino_value',
											x: 400,
											y: 5
										},
										{
											xtype: 'numberfield',
											width: 75,
											inputId: 'UsBAOtros',
											name: 'pis_otros_anual',
											fieldLabel: '',
											labelAlign: 'right',
											labelWidth: 40,
											allowDecimals: false,
											minValue: 0,
											x: 455,
											y: 35
										}
									]
								},
								{
									xtype: 'textfield',
									width: 610,
									inputId: 'UsBReceptorAguasProceso',
									name: 'pis_receptor',
									fieldLabel: 'RECEPTOR DE AGUAS LUEGO DEL PROCESO',
									labelAlign: 'right',
									labelWidth: 250,
									emptyText: '',
									x: 145,
									y: 90
								},
								{
									xtype: 'combobox',
									width: 230,
									inputId: 'UsBImpactosAmbientales',
									name: 'pis_impactos_yn',
									fieldLabel: 'IMPACTOS AMBIENTALES',
									labelAlign: 'right',
									labelWidth: 150,
									displayField: 'sino_display',
									forceSelection: true,
									queryMode: 'local',
									store: 'SiNo',
									valueField: 'sino_value',
									x: 245,
									y: 120
								},
								{
									xtype: 'numberfield',
									width: 180,
									inputId: 'UsBNoEstanques',
									name: 'pis_estanques',
									fieldLabel: 'No. ESTANQUES',
									labelAlign: 'right',
									allowDecimals: false,
									minValue: 0,
									x: 295,
									y: 150
								},
								{
									xtype: 'numberfield',
									width: 210,
									inputId: 'UsBAreaTotal',
									name: 'pis_area_total',
									fieldLabel: 'AREA TOTAL (m2)',
									labelAlign: 'right',
									labelWidth: 110,
									minValue: 0,
									x: 490,
									y: 150
								},
								{
									xtype: 'fieldset',
									height: 120,
									width: 360,
									layout: {
										type: 'absolute'
									},
									title: 'LOCALIZACION DEL PROCESO DE ACUACULTURA',
									x: 800,
									y: 70,
									items: [
										{
											xtype: 'numberfield',
											width: 230,
											inputId: 'UsBCota',
											name: 'pis_cota',
											fieldLabel: 'COTA (msnm)',
											labelAlign: 'right',
											minValue: 0,
											x: 10,
											y: 5
										},
										{
											xtype: 'numberfield',
											width: 230,
											inputId: 'UsBLatitud',
											name: 'pis_latitud',
											fieldLabel: 'LATITUD (m)',
											labelAlign: 'right',
											minValue: 0,
											x: 10,
											y: 35
										},
										{
											xtype: 'numberfield',
											width: 230,
											inputId: 'UsBLongitud',
											name: 'pis_longitud',
											fieldLabel: 'LONGITUD (m)',
											labelAlign: 'right',
											minValue: 0,
											x: 10,
											y: 65
										}
									]
								}
							]
						},
						{
							xtype: 'fieldset',
							height: 150,
							id: 'c-agua-envasada',
							width: 345,
							layout: {
								type: 'absolute'
							},
							title: 'C. AGUA ENVASADA',
							x: 10,
							y: 390,
							items: [
								{
									xtype: 'numberfield',
									width: 230,
									inputId: 'UsCCaudalMedido',
									name: 'env_caudal_medido',
									fieldLabel: 'CAUDAL MEDIDO (l/s)',
									labelAlign: 'right',
									labelWidth: 140,
									minValue: 0,
									x: 40,
									y: 5
								},
								{
									xtype: 'numberfield',
									width: 280,
									inputId: 'UsCProduccionAnual',
									name: 'env_anual',
									fieldLabel: 'PRODUCCION ANUAL (botellas)',
									labelAlign: 'right',
									labelWidth: 190,
									minValue: 0,
									x: -10,
									y: 35
								}
							]
						},
						{
							xtype: 'fieldset',
							height: 150,
							id: 'd-termales',
							width: 810,
							layout: {
								type: 'absolute'
							},
							title: 'D. TERMALES',
							x: 390,
							y: 390,
							items: [
								{
									xtype: 'numberfield',
									width: 300,
									inputId: 'UsDCaudalMedido',
									name: 'ter_caudal_medido',
									fieldLabel: 'CAUDAL MEDIDO (l/s)',
									labelAlign: 'right',
									labelWidth: 140,
									minValue: 0,
									x: 45,
									y: 5
								},
								{
									xtype: 'numberfield',
									width: 300,
									inputId: 'UsDDiasPorSemana',
									name: 'ter_dias',
									fieldLabel: 'DIAS POR SEMANA',
									labelAlign: 'right',
									labelWidth: 140,
									allowDecimals: false,
									minValue: 0,
									x: 45,
									y: 35
								},
								{
									xtype: 'numberfield',
									width: 320,
									inputId: 'UsDVolumenSemanal',
									name: 'ter_volumen',
									fieldLabel: 'VOLUMEN SEMANAL (m3)',
									labelAlign: 'right',
									labelWidth: 160,
									minValue: 0,
									x: 25,
									y: 65
								},
								{
									xtype: 'fieldset',
									height: 120,
									width: 360,
									layout: {
										type: 'absolute'
									},
									title: 'LOCALIZACION DEL SITIO DE DESCARGA',
									x: 420,
									y: 0,
									items: [
										{
											xtype: 'numberfield',
											width: 230,
											inputId: 'UsDCota',
											name: 'ter_cota',
											fieldLabel: 'COTA (msnm)',
											labelAlign: 'right',
											minValue: 0,
											x: 10,
											y: 5
										},
										{
											xtype: 'numberfield',
											width: 230,
											inputId: 'UsDLatitud',
											name: 'ter_latitud',
											fieldLabel: 'LATITUD (m)',
											labelAlign: 'right',
											minValue: 0,
											x: 10,
											y: 35
										},
										{
											xtype: 'numberfield',
											width: 230,
											inputId: 'UsDLongitud',
											name: 'ter_longitud',
											fieldLabel: 'LONGITUD (m)',
											labelAlign: 'right',
											minValue: 0,
											x: 10,
											y: 65
										}
									]
								}
							]
						},
						{
							xtype: 'fieldset',
							height: 100,
							id: 'e-industria',
							width: 1190,
							layout: {
								type: 'absolute'
							},
							title: 'E. INDUSTRIA',
							x: 10,
							y: 560,
							items: [
								{
									xtype: 'numberfield',
									width: 230,
									inputId: 'UsECaudalMedido',
									name: 'ind_caudal_medido',
									fieldLabel: 'CAUDAL MEDIDO (l/s)',
									labelAlign: 'right',
									labelWidth: 140,
									minValue: 0,
									x: 20,
									y: 5
								},
								{
									xtype: 'combobox',
									width: 400,
									inputId: 'UsEUsoIndustrial',
									name: 'ind_uso',
									fieldLabel: 'USO INDUSTRIAL',
									labelAlign: 'right',
									labelWidth: 140,
									displayField: 'par_descripcion',
									forceSelection: true,
									queryMode: 'local',
									store: 'UsoIndustrial',
									valueField: 'par_id',
									x: 280,
									y: 5
								},
								{
									xtype: 'textfield',
									width: 400,
									inputId: 'UsEReceptorAguasDescarga',
									name: 'ind_receptor',
									fieldLabel: 'RECEPTOR DE AGUAS DE LA DESCARGA',
									labelAlign: 'right',
									labelWidth: 140,
									x: 280,
									y: 35
								},
								{
									xtype: 'combobox',
									width: 390,
									inputId: 'UsEExplotacionMinera',
									name: 'ind_explotacion',
									fieldLabel: 'EXPLOTACION MINERA',
									labelAlign: 'right',
									labelWidth: 140,
									displayField: 'par_descripcion',
									forceSelection: true,
									queryMode: 'local',
									store: 'ExplotacionMinera',
									valueField: 'par_id',
									x: 700,
									y: 5
								}
							]
						},
						{
							xtype: 'fieldset',
							height: 125,
							id: 'f-riego',
							width: 1190,
							layout: {
								type: 'absolute'
							},
							title: 'F. RIEGO',
							x: 10,
							y: 680,
							items: [
								{
									xtype: 'numberfield',
									width: 230,
									inputId: 'UsFCaudalMedido',
									name: 'rie_caudal_medido',
									fieldLabel: 'CAUDAL MEDIDO (l/s)',
									labelAlign: 'right',
									labelWidth: 140,
									minValue: 0,
									x: -5,
									y: 5
								},
								{
									xtype: 'numberfield',
									width: 220,
									inputId: 'UsFAreaRiego',
									name: 'rie_area',
									fieldLabel: 'AREA DE RIEGO (Has)',
									labelAlign: 'right',
									labelWidth: 130,
									minValue: 0,
									x: 5,
									y: 35
								},
								{
									xtype: 'radiogroup',
									height: 24,
									id: 'UsFTipoRegante',
									width: 274,
									layout: {
										type: 'absolute'
									},
									fieldLabel: 'TIPO DE REGANTE',
									labelAlign: 'right',
									labelWidth: 120,
									x: 15,
									y: 65,
									items: [
										{
											xtype: 'radiofield',
											name: 'rie_tipo_regante',
											boxLabel: 'Estatal',
											inputValue: 47,
											x: 0,
											y: 0
										},
										{
											xtype: 'radiofield',
											name: 'rie_tipo_regante',
											boxLabel: 'Particular',
											inputValue: 48,
											x: 70,
											y: 0
										}
									]
								},
								{
									xtype: 'radiogroup',
									height: 54,
									id: 'UsFFasesRiego',
									itemId: 'UsFFasesRiego',
									width: 354,
									layout: {
										type: 'absolute'
									},
									fieldLabel: 'FASES DEL SISTEMA DE RIEGO',
									labelAlign: 'right',
									labelWidth: 120,
									x: 315,
									y: 5,
									items: [
										{
											xtype: 'radiofield',
											name: 'rie_estado_sistema_riego',
											boxLabel: 'Operando',
											inputValue: 40,
											x: 10,
											y: 0
										},
										{
											xtype: 'radiofield',
											name: 'rie_estado_sistema_riego',
											boxLabel: 'En reparación',
											inputValue: 41,
											x: 100,
											y: 0
										},
										{
											xtype: 'radiofield',
											name: 'rie_estado_sistema_riego',
											value: 'En Construccion',
											boxLabel: 'En construcción',
											inputValue: 42,
											x: 100,
											y: 20
										}
									]
								},
								{
									xtype: 'textfield',
									width: 200,
									inputId: 'UsFCultivo1',
									name: 'rie_tipo_cultivo1',
									fieldLabel: 'CULTIIVO 1',
									labelAlign: 'right',
									labelWidth: 80,
									x: 310,
									y: 65
								},
								{
									xtype: 'textfield',
									width: 200,
									inputId: 'UsFCultivo2',
									name: 'rie_tipo_cultivo2',
									fieldLabel: 'CULTIIVO 2',
									labelAlign: 'right',
									labelWidth: 80,
									x: 510,
									y: 65
								},
								{
									xtype: 'checkboxgroup',
									height: 44,
									id: 'UsFMetodosRiego',
									width: 304,
									layout: {
										type: 'absolute'
									},
									fieldLabel: 'METODOS DE RIEGO',
									labelAlign: 'right',
									x: 720,
									y: 5,
									items: [
										{
											xtype: 'checkboxfield',
											inputId: 'UsFMRGravedad',
											name: 'rie_metodo_riego_gravedad',
											boxLabel: 'Gravedad',
											inputValue: 1,
											uncheckedValue: 0,
											x: 10,
											y: -1
										},
										{
											xtype: 'checkboxfield',
											inputId: 'UsFMRAspercion',
											name: 'rie_metodo_riego_aspersion',
											boxLabel: 'Asperción',
											inputValue: 1,
											uncheckedValue: 0,
											x: 100,
											y: -1
										},
										{
											xtype: 'checkboxfield',
											inputId: 'UsFMRGoteo',
											name: 'rie_metodo_riego_goteo',
											boxLabel: 'Goteo',
											inputValue: 1,
											uncheckedValue: 0,
											x: 10,
											y: 20
										},
										{
											xtype: 'checkboxfield',
											inputId: 'UsFMROtros',
											name: 'rie_metodo_riego_otros',
											boxLabel: 'Otros',
											inputValue: 1,
											uncheckedValue: 0,
											x: 100,
											y: 20
										}
									]
								},
								{
									xtype: 'numberfield',
									width: 150,
									inputId: 'UsFFamilias',
									name: 'rie_nfamilias',
									fieldLabel: 'FAMILIAS',
									labelAlign: 'right',
									labelWidth: 80,
									allowDecimals: false,
									minValue: 0,
									x: 740,
									y: 65
								},
								{
									xtype: 'numberfield',
									width: 270,
									inputId: 'UsFDotacion',
									name: 'rie_dotacion',
									fieldLabel: 'DOTACION (l/Hab/Día)',
									labelAlign: 'right',
									labelWidth: 160,
									minValue: 0,
									x: 885,
									y: 65
								}
							]
						},
						{
							xtype: 'fieldset',
							height: 115,
							id: 'g-fuerza-mecanica',
							width: 530,
							layout: {
								type: 'absolute'
							},
							title: 'G. FUERZA MECANICA',
							x: 10,
							y: 825,
							items: [
								{
									xtype: 'numberfield',
									width: 230,
									inputId: 'UsGCaudalMedido',
									name: 'mec_caudal_medido',
									fieldLabel: 'CAUDAL MEDIDO (l/s)',
									labelAlign: 'right',
									labelWidth: 140,
									minValue: 0,
									x: -5,
									y: 5
								},
								{
									xtype: 'numberfield',
									width: 230,
									inputId: 'UsGPotenciaTrabajo',
									name: 'mec_potencia',
									fieldLabel: 'POTENCIA DE TRABAJO (hp)',
									labelAlign: 'right',
									labelWidth: 170,
									minValue: 0,
									x: 270,
									y: 5
								},
								{
									xtype: 'numberfield',
									width: 200,
									inputId: 'UsGAlturaCaida',
									name: 'mec_altura',
									fieldLabel: 'ALTURA DE CAIDA (m)',
									labelAlign: 'right',
									labelWidth: 140,
									minValue: 0,
									x: 300,
									y: 35
								}
							]
						},
						{
							xtype: 'fieldset',
							height: 115,
							id: 'h-abrevadero',
							width: 620,
							layout: {
								type: 'absolute'
							},
							title: 'H. ABREVADERO',
							x: 580,
							y: 825,
							items: [
								{
									xtype: 'numberfield',
									width: 230,
									inputId: 'UsHCaudalMedido',
									name: 'abr_caudal_medido',
									fieldLabel: 'CAUDAL MEDIDO (l/s)',
									labelAlign: 'right',
									labelWidth: 140,
									minValue: 0,
									x: 0,
									y: 5
								},
								{
									xtype: 'fieldcontainer',
									height: 84,
									id: 'UsHSemovientes',
									itemId: 'UsHSemovientes',
									width: 324,
									layout: {
										type: 'absolute'
									},
									fieldLabel: 'SEMOVIENTES',
									x: 275,
									y: 5,
									items: [
										{
											xtype: 'numberfield',
											width: 110,
											inputId: 'UsHSVacuno',
											name: 'abr_sem_vacuno',
											fieldLabel: 'Vacuno',
											labelAlign: 'right',
											labelWidth: 50,
											allowDecimals: false,
											minValue: 0,
											x: -18,
											y: 0
										},
										{
											xtype: 'numberfield',
											width: 110,
											inputId: 'UsHSCaprino',
											name: 'abr_sem_caprino',
											fieldLabel: 'Caprino',
											labelAlign: 'right',
											labelWidth: 50,
											allowDecimals: false,
											minValue: 0,
											x: -18,
											y: 30
										},
										{
											xtype: 'numberfield',
											width: 110,
											inputId: 'UsHSBovino',
											name: 'abr_sem_bovino',
											fieldLabel: 'Bovino',
											labelAlign: 'right',
											labelWidth: 50,
											allowDecimals: false,
											minValue: 0,
											x: -18,
											y: 60
										},
										{
											xtype: 'numberfield',
											width: 110,
											inputId: 'UsHSPorcino',
											name: 'abr_sem_porcino',
											fieldLabel: 'Porcino',
											labelAlign: 'right',
											labelWidth: 50,
											allowDecimals: false,
											minValue: 0,
											x: 100,
											y: 0
										},
										{
											xtype: 'numberfield',
											width: 110,
											inputId: 'UsHSAves',
											name: 'abr_sem_aves',
											fieldLabel: 'Aves',
											labelAlign: 'right',
											labelWidth: 50,
											allowDecimals: false,
											minValue: 0,
											x: 100,
											y: 30
										},
										{
											xtype: 'numberfield',
											width: 110,
											inputId: 'UsHSOtros',
											name: 'abr_sem_otros',
											fieldLabel: 'Otros',
											labelAlign: 'right',
											labelWidth: 50,
											allowDecimals: false,
											minValue: 0,
											x: 100,
											y: 60
										}
									]
								}
							]
						},
						{
							xtype: 'fieldset',
							height: 150,
							id: 'i-hidroelectricas',
							width: 1190,
							layout: {
								type: 'absolute'
							},
							title: 'I. HIDROELECTRICAS',
							x: 10,
							y: 960,
							items: [
								{
									xtype: 'numberfield',
									width: 230,
									inputId: 'UsICaudalMedido',
									name: 'hid_caudal_medido',
									fieldLabel: 'CAUDAL MEDIDO (l/s)',
									labelAlign: 'right',
									labelWidth: 140,
									minValue: 0,
									x: -4,
									y: 5
								},
								{
									xtype: 'textfield',
									width: 320,
									inputId: 'UsICentralHidroelectrica',
									name: 'hid_central',
									fieldLabel: 'CENTRAL HIDROELECTRICA',
									labelAlign: 'right',
									labelWidth: 160,
									x: 270,
									y: 5
								},
								{
									xtype: 'numberfield',
									width: 180,
									inputId: 'UsIPotencia',
									name: 'hid_potencia',
									fieldLabel: 'POTENCIA (Kw)',
									labelAlign: 'right',
									minValue: 0,
									x: 600,
									y: 5
								},
								{
									xtype: 'numberfield',
									width: 320,
									inputId: 'UsIAlturaCaida',
									name: 'hid_altura',
									fieldLabel: 'ALTURA DE CAIDA (m)',
									labelAlign: 'right',
									labelWidth: 160,
									minValue: 0,
									x: 270,
									y: 35
								},
								{
									xtype: 'textfield',
									width: 510,
									inputId: 'UsIReceptorAguasDescarga',
									name: 'hid_receptor',
									fieldLabel: 'RECEPTOR DE AGUAS DE LA DESCARGA',
									labelAlign: 'right',
									labelWidth: 160,
									x: 270,
									y: 65
								},
								{
									xtype: 'fieldset',
									height: 120,
									width: 340,
									layout: {
										type: 'absolute'
									},
									title: 'LOCALIZACION DEL SITIO DE DESCARGA',
									x: 820,
									y: 0,
									items: [
										{
											xtype: 'numberfield',
											width: 230,
											inputId: 'UsICota',
											name: 'hid_cota',
											fieldLabel: 'COTA (msnm)',
											labelAlign: 'right',
											minValue: 0,
											x: 10,
											y: 5
										},
										{
											xtype: 'numberfield',
											width: 230,
											inputId: 'UsILatitud',
											name: 'hid_latitud',
											fieldLabel: 'LATITUD (m)',
											labelAlign: 'right',
											minValue: 0,
											x: 10,
											y: 35
										},
										{
											xtype: 'numberfield',
											width: 230,
											inputId: 'UsILongitud',
											name: 'hid_longitud',
											fieldLabel: 'LONGITUD (m)',
											labelAlign: 'right',
											minValue: 0,
											x: 10,
											y: 65
										}
									]
								}
							]
						}
					]
				},
				{
					xtype: 'fieldset',
					height: 550,
					id: 'FuenteHidrica',
					width: 1230,
					layout: {
						type: 'absolute'
					},
					title: 'III FUENTE HIDRICA',
					x: 10,
					y: 1530,
					items: [
						{
							xtype: 'textfield',
							width: 790,
							inputId: 'FuHiNombre',
							name: 'nombre',
							fieldLabel: 'NOMBRE',
							labelAlign: 'right',
							x: 10,
							y: 5
						},
						{
							xtype: 'checkboxgroup',
							height: 54,
							id: 'FuHiTipoFuenteOrigen',
							width: 744,
							layout: {
								type: 'absolute'
							},
							fieldLabel: 'TIPO DE FUENTE DE ORIGEN',
							labelAlign: 'right',
							x: 10,
							y: 40,
							items: [
								{
									xtype: 'checkboxfield',
									inputId: 'FuHiQuebrada',
									name: 'tipo_fuente_quebrada',
									boxLabel: 'Quebrada',
									inputValue: 1,
									uncheckedValue: 0,
									x: 10,
									y: 0
								},
								{
									xtype: 'checkboxfield',
									inputId: 'FuHiPozo',
									name: 'tipo_fuente_pozo',
									boxLabel: 'Pozo',
									inputValue: 1,
									uncheckedValue: 0,
									x: 100,
									y: 0
								},
								{
									xtype: 'checkboxfield',
									inputId: 'FuHiLago',
									name: 'tipo_fuente_lago',
									boxLabel: 'Lago, laguna',
									inputValue: 1,
									uncheckedValue: 0,
									x: 180,
									y: 0
								},
								{
									xtype: 'checkboxfield',
									inputId: 'FuHiDrenajes',
									name: 'tipo_fuente_drenajes',
									boxLabel: 'Drenajes',
									inputValue: 1,
									uncheckedValue: 0,
									x: 280,
									y: 0
								},
								{
									xtype: 'checkboxfield',
									inputId: 'FuHiCanales',
									name: 'tipo_fuente_canales',
									boxLabel: 'Canales',
									inputValue: 1,
									uncheckedValue: 0,
									x: 380,
									y: 0
								},
								{
									xtype: 'checkboxfield',
									inputId: 'FuHiRio',
									name: 'tipo_fuente_rio',
									boxLabel: 'Río',
									inputValue: 1,
									uncheckedValue: 0,
									x: 10,
									y: 20
								},
								{
									xtype: 'checkboxfield',
									inputId: 'FuHiVertiente',
									name: 'tipo_fuente_vertiente',
									boxLabel: 'Vertiente',
									inputValue: 1,
									uncheckedValue: 0,
									x: 100,
									y: 20
								},
								{
									xtype: 'checkboxfield',
									inputId: 'FuHiEstero',
									name: 'tipo_fuente_estero',
									boxLabel: 'Estero',
									inputValue: 1,
									uncheckedValue: 0,
									x: 180,
									y: 20
								},
								{
									xtype: 'checkboxfield',
									inputId: 'FuHiRemanentes',
									name: 'tipo_fuente_remanentes',
									boxLabel: 'Remanentes',
									inputValue: 1,
									uncheckedValue: 0,
									x: 280,
									y: 20
								},
								{
									xtype: 'checkboxfield',
									inputId: 'FuHiOtros',
									name: 'tipo_fuente_otros',
									boxLabel: 'Otros',
									inputValue: 1,
									uncheckedValue: 0,
									x: 380,
									y: 20
								}
							]
						},
						{
							xtype: 'textfield',
							width: 790,
							inputId: 'FuHiSectorCaptacion',
							name: 'sector',
							fieldLabel: 'SECTOR DE LA CAPTACION',
							labelAlign: 'right',
							x: 10,
							y: 95
						},
						{
							xtype: 'fieldset',
							height: 120,
							width: 360,
							layout: {
								type: 'absolute'
							},
							title: 'LOCALIZACION DE LA BOCATOMA',
							x: 840,
							y: 0,
							items: [
								{
									xtype: 'numberfield',
									width: 230,
									inputId: 'FuHiCota',
									name: 'cota',
									fieldLabel: 'COTA (msnm)',
									labelAlign: 'right',
									minValue: 0,
									x: 10,
									y: 5
								},
								{
									xtype: 'numberfield',
									width: 230,
									inputId: 'FuHiLatitud',
									name: 'latitud',
									fieldLabel: 'LATITUD (m)',
									labelAlign: 'right',
									minValue: 0,
									x: 10,
									y: 35
								},
								{
									xtype: 'numberfield',
									width: 230,
									inputId: 'FuHiLongitud',
									name: 'longitud',
									fieldLabel: 'LONGITUD (m)',
									labelAlign: 'right',
									minValue: 0,
									x: 10,
									y: 65
								}
							]
						},
						{
							xtype: 'fieldset',
							height: 180,
							width: 790,
							layout: {
								type: 'absolute'
							},
							title: 'OBRA DE CAPTACION',
							x: 10,
							y: 140,
							items: [
								{
									xtype: 'combobox',
									width: 230,
									inputId: 'FuHiObCapExistencia',
									name: 'existe_captacion_yn',
									fieldLabel: 'EXISTENCIA',
									labelAlign: 'right',
									labelWidth: 170,
									displayField: 'sino_display',
									forceSelection: true,
									queryMode: 'local',
									store: 'SiNo',
									valueField: 'sino_value',
									x: -53,
									y: 5
								},
								{
									xtype: 'checkboxgroup',
									height: 64,
									id: 'FuHiObCapTipo',
									width: 754,
									layout: {
										type: 'absolute'
									},
									fieldLabel: 'TIPO',
									labelAlign: 'right',
									labelWidth: 150,
									x: -33,
									y: 45,
									items: [
										{
											xtype: 'checkboxfield',
											inputId: 'FuHiObCapTanques',
											name: 'tipo_captacion_tanques',
											boxLabel: 'Tanques',
											inputValue: 1,
											uncheckedValue: 0,
											x: -1,
											y: 0
										},
										{
											xtype: 'checkboxfield',
											inputId: 'FuHiObCapCompuertas',
											name: 'tipo_captacion_compuertas',
											boxLabel: 'Compuertas',
											inputValue: 1,
											uncheckedValue: 0,
											x: -1,
											y: 20
										},
										{
											xtype: 'checkboxfield',
											width: 140,
											inputId: 'FuHiObCapTuberias',
											name: 'tipo_captacion_tuberias',
											boxLabel: 'Tuberías, mangueras',
											inputValue: 1,
											uncheckedValue: 0,
											x: 90,
											y: 0
										},
										{
											xtype: 'checkboxfield',
											inputId: 'FuHiObCapOvalos',
											name: 'tipo_captacion_ovalos',
											boxLabel: 'Ovalos',
											inputValue: 1,
											uncheckedValue: 0,
											x: 90,
											y: 20
										},
										{
											xtype: 'checkboxfield',
											width: 140,
											inputId: 'FuHiObCapEquipos',
											name: 'tipo_captacion_equipos',
											boxLabel: 'Equipos de bombeo',
											inputValue: 1,
											uncheckedValue: 0,
											x: 230,
											y: 0
										},
										{
											xtype: 'checkboxfield',
											inputId: 'FuHiObCapDiques',
											name: 'tipo_captacion_diques',
											boxLabel: 'Diques, muros, embalses',
											inputValue: 1,
											uncheckedValue: 0,
											x: 230,
											y: 20
										},
										{
											xtype: 'checkboxfield',
											inputId: 'FuHiObCapAcequias',
											name: 'tipo_captacion_acequias',
											boxLabel: 'Acequias, canales',
											inputValue: 1,
											uncheckedValue: 0,
											x: 390,
											y: 0
										},
										{
											xtype: 'checkboxfield',
											inputId: 'FuHiObCapOtros',
											name: 'tipo_captacion_otros',
											boxLabel: 'Otros',
											inputValue: 1,
											uncheckedValue: 0,
											x: 390,
											y: 20
										}
									]
								},
								{
									xtype: 'radiogroup',
									height: 54,
									id: 'FuHiObCapEstadoActual',
									width: 354,
									layout: {
										type: 'absolute'
									},
									fieldLabel: 'ESTADO ACTUAL',
									labelAlign: 'right',
									labelWidth: 150,
									x: -33,
									y: 100,
									items: [
										{
											xtype: 'radiofield',
											name: 'estado_captacion',
											boxLabel: 'Buena',
											inputValue: 72,
											x: -1,
											y: 0
										},
										{
											xtype: 'radiofield',
											name: 'estado_captacion',
											boxLabel: 'Mala',
											inputValue: 74,
											x: -1,
											y: 20
										},
										{
											xtype: 'radiofield',
											width: 90,
											name: 'estado_captacion',
											boxLabel: 'Regular',
											inputValue: 73,
											x: 60,
											y: 0
										},
										{
											xtype: 'radiofield',
											name: 'estado_captacion',
											boxLabel: 'Excelente',
											inputValue: 71,
											x: 60,
											y: 20
										}
									]
								},
								{
									xtype: 'radiogroup',
									height: 54,
									id: 'FuHiObCapOperacionActual',
									width: 354,
									layout: {
										type: 'absolute'
									},
									fieldLabel: 'OPERACION ACTUAL',
									labelAlign: 'right',
									labelWidth: 150,
									x: 300,
									y: 100,
									items: [
										{
											xtype: 'radiofield',
											name: 'operacion_actual',
											boxLabel: 'Normal',
											inputValue: 75,
											x: -1,
											y: 0
										},
										{
											xtype: 'radiofield',
											name: 'operacion_actual',
											boxLabel: 'Temporal',
											inputValue: 77,
											x: -1,
											y: 20
										},
										{
											xtype: 'radiofield',
											width: 90,
											name: 'operacion_actual',
											boxLabel: 'Desaparecida',
											inputValue: 76,
											x: 80,
											y: 0
										},
										{
											xtype: 'radiofield',
											name: 'operacion_actual',
											boxLabel: 'Reparación',
											inputValue: 78,
											x: 80,
											y: 20
										}
									]
								}
							]
						},
						{
							xtype: 'radiogroup',
							height: 74,
							id: 'FuHiMetodosMedicionCaudales',
							width: 354,
							layout: {
								type: 'absolute'
							},
							fieldLabel: 'METODOS DE MEDICION DE CAUDALES',
							labelAlign: 'right',
							labelWidth: 150,
							x: 825,
							y: 155,
							items: [
								{
									xtype: 'radiofield',
									name: 'metodo_medicion',
									boxLabel: 'Flotador',
									inputValue: 67,
									x: -1,
									y: 0
								},
								{
									xtype: 'radiofield',
									name: 'metodo_medicion',
									boxLabel: 'Molinete',
									inputValue: 69,
									x: -1,
									y: 20
								},
								{
									xtype: 'radiofield',
									width: 90,
									name: 'metodo_medicion',
									boxLabel: 'Volumétrico',
									inputValue: 68,
									x: 90,
									y: 0
								},
								{
									xtype: 'radiofield',
									name: 'metodo_medicion',
									boxLabel: 'Otros',
									inputValue: 70,
									x: 90,
									y: 20
								}
							]
						},
						{
							xtype: 'radiogroup',
							height: 54,
							id: 'FuHiTenenciaTierra',
							width: 354,
							layout: {
								type: 'absolute'
							},
							fieldLabel: 'TENENCIA DE LA TIERRA',
							labelAlign: 'right',
							labelWidth: 150,
							x: 825,
							y: 225,
							items: [
								{
									xtype: 'radiofield',
									name: 'tenencia',
									boxLabel: 'Privado',
									inputValue: 79,
									x: -1,
									y: 0
								},
								{
									xtype: 'radiofield',
									name: 'tenencia',
									boxLabel: 'Comunitario',
									inputValue: 80,
									x: -1,
									y: 20
								},
								{
									xtype: 'radiofield',
									width: 90,
									name: 'tenencia',
									boxLabel: 'Comunal',
									inputValue: 81,
									x: 90,
									y: 0
								},
								{
									xtype: 'radiofield',
									name: 'tenencia',
									boxLabel: 'Area protegida',
									inputValue: 82,
									x: 90,
									y: 20
								}
							]
						},
						{
							xtype: 'numberfield',
							width: 250,
							inputId: 'FuHiAnioInicioOperacion',
							name: 'anio_inicio',
							fieldLabel: 'AÑO DE INICIO DE OPERACION',
							labelAlign: 'right',
							labelWidth: 180,
							enforceMaxLength: true,
							maxLength: 4,
							minLength: 4,
							allowDecimals: false,
							minText: 2000,
							minValue: 0,
							x: 10,
							y: 335
						},
						{
							xtype: 'textfield',
							width: 530,
							inputId: 'FuHiPropietario',
							name: 'propietario',
							fieldLabel: 'PROPIETARIO',
							labelAlign: 'right',
							x: 270,
							y: 335
						},
						{
							xtype: 'fieldset',
							height: 120,
							width: 1190,
							layout: {
								type: 'absolute'
							},
							title: 'CONTAMINACION Y CARATERIZACION AMBIENTAL',
							x: 10,
							y: 385,
							items: [
								{
									xtype: 'combobox',
									width: 260,
									inputId: 'FuHiPercepcionContaminacion',
									name: 'percepcion_contaminacion_yn',
									fieldLabel: 'PERCEPCION DE CONTAMINACION',
									labelAlign: 'right',
									labelWidth: 200,
									displayField: 'sino_display',
									forceSelection: true,
									queryMode: 'local',
									store: 'SiNo',
									valueField: 'sino_value',
									x: 0,
									y: 5
								},
								{
									xtype: 'textfield',
									width: 240,
									inputId: 'FuHiColorAgua',
									name: 'color_agua',
									fieldLabel: 'COLOR DEL AGUA',
									labelAlign: 'right',
									labelWidth: 110,
									x: 90,
									y: 35
								},
								{
									xtype: 'textfield',
									width: 230,
									inputId: 'FuHiOlorAgua',
									name: 'olor_agua',
									fieldLabel: 'OLOR DEL AGUA',
									labelAlign: 'right',
									x: 100,
									y: 65
								},
								{
									xtype: 'combobox',
									width: 450,
									inputId: 'FuHiSituacionCobertura',
									name: 'cobertura_vegetal',
									fieldLabel: 'SITUACION DE LA COBERTURA VEGETAL DOMINANTE',
									labelAlign: 'right',
									labelWidth: 310,
									displayField: 'par_descripcion',
									forceSelection: true,
									queryMode: 'local',
									store: 'CoberturaVegetal',
									valueField: 'par_id',
									x: 340,
									y: 5
								},
								{
									xtype: 'textfield',
									width: 440,
									inputId: 'FuHiTipoContaminacion',
									name: 'tipo_contaminacion',
									fieldLabel: 'TIPO DE CONTAMINACION',
									labelAlign: 'right',
									labelWidth: 300,
									x: 350,
									y: 35
								},
								{
									xtype: 'textfield',
									width: 360,
									inputId: 'FuHiEspecieFlora',
									name: 'flora',
									fieldLabel: 'ESPECIE DE FLORA DOMINANTE',
									labelAlign: 'right',
									labelWidth: 190,
									x: 800,
									y: 5
								}
							]
						}
					]
				},
				{
					xtype: 'fieldset',
					height: 150,
					id: 'Anexos',
					width: 600,
					layout: {
						type: 'absolute'
					},
					title: 'IV ANEXO FOTOGRAFICO Y/O CROQUIS',
					x: 10,
					y: 2110,
					items: [
						{
							xtype: 'filefield',
							width: 410,
							inputId: 'AnFotografia',
							name: 'ruta',
							fieldLabel: 'FOTOGRAFIA',
							labelAlign: 'right',
							buttonText: 'Buscar...',
							x: -13,
							y: 5
						}
					]
				},
				{
					xtype: 'textareafield',
					height: 150,
					width: 600,
					inputId: 'GeReSoObservaciones',
					name: 'con_observaciones',
					fieldLabel: 'OBSERVACIONES',
					labelAlign: 'top',
					labelWidth: 110,
					x: 640,
					y: 2110
				},
				{
					xtype: 'fieldset',
					height: 120,
					id: 'RepresentanteJunta',
					width: 600,
					layout: {
						type: 'absolute'
					},
					title: 'REPRESENTANTE JUNTA PARROQUIAL',
					x: 10,
					y: 2290,
					items: [
						{
							xtype: 'textfield',
							width: 530,
							inputId: 'ReJuPaNombresApellidos',
							name: 'con_representante_junta',
							fieldLabel: 'NOMBRES/APELLIDOS',
							labelAlign: 'right',
							labelWidth: 140,
							x: 40,
							y: 5
						},
						{
							xtype: 'textfield',
							width: 560,
							inputId: 'ReJuPaDireccionDomiciliaria',
							name: 'con_direccion',
							fieldLabel: 'DIRECCION DOMICILIARIA',
							labelAlign: 'right',
							labelWidth: 170,
							x: 10,
							y: 35
						},
						{
							xtype: 'textfield',
							width: 450,
							inputId: 'ReJuPaTelefono',
							name: 'con_telefonos',
							fieldLabel: 'TLF CONVENCIONAL/CELULAR',
							labelAlign: 'right',
							labelWidth: 180,
							x: 0,
							y: 65
						}
					]
				},
				{
					xtype: 'fieldset',
					height: 120,
					id: 'ValidacionDatos',
					width: 600,
					layout: {
						type: 'absolute'
					},
					title: 'VALIDACION DE DATOS',
					x: 640,
					y: 2290,
					items: [
						{
							xtype: 'textfield',
							width: 570,
							inputId: 'VaDaResponsable',
							name: 'con_responsable_validacion',
							fieldLabel: 'RESPONSABLE',
							labelAlign: 'right',
							labelWidth: 140,
							x: -45,
							y: 5
						},
						{
							xtype: 'datefield',
							width: 300,
							inputId: 'VaDaFecha',
							name: 'con_fecha_validacion',
							fieldLabel: 'FECHA',
							labelAlign: 'right',
							labelWidth: 170,
							format: 'Y-m-d',
							x: -75,
							y: 35
						}
					]
				},
				{
					xtype: 'container',
					height: 14,
					id: 'contenedor',
					width: 1234,
					x: 10,
					y: 2430
				}
			]
		});

		me.callParent(arguments);
	}
});